// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// hello_controller.js（個別の Stimulus コントローラ）を読み込む
import HelloController from "./hello_controller"

// Stimulus に "hello" という名前でコントローラを登録する
// これにより <div data-controller="hello"> が有効になる
application.register("hello", HelloController)
